language: node_js
node_js:
- "12"
env:
  global:
  - NPM_TAG=latest
  - RELEASE_TIMESTAMP="$(date +'%Y%m%d%H%M%S')"
addons:
  chrome: stable
cache:
  directories:
  - node_modules
install:
- npm run fetch
before_deploy:
- VPKG=$($(npm bin)/json -f package.json version)
- export RELEASE_VERSION=${VPKG}-prerelease.${RELEASE_TIMESTAMP}
- npm --no-git-tag-version version $RELEASE_VERSION
- npm run deploy
deploy:
- provider: npm
  on:
    branch:
    - main
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  tag: $NPM_TAG
- provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: dist
